### ISSUE TITLE
Remove category "Language Packs"

### ISSUE THREAD

**Issue by gregvanl** [JonathanWilbur/vscode-asn1#4]
The category "Language Packs" is for extensions that provide localized display languages such as German and Japanese. Using category "Programming Languages" is correct for extensions which contribute programming language features.

![image](https://user-images.githubusercontent.com/12818376/55659960-cc9dbf80-57b8-11e9-8c76-de0ac7ee717d.png)

**Comment by JonathanWilbur** [comment]
This has been fixed. Thank you for pointing this out!
